### ISSUE TITLE
python 3.x support

### ISSUE THREAD

**Issue by pahaz** [landscapeio/prospector#107]
(venv)root@precise64:/vagrant# python --version
    Python 3.2.3
    (venv)root@precise64:/vagrant# prospector
    Traceback (most recent call last):
      File "/var/lib/wflow/venv/bin/prospector", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 2829, in <module>
        working_set = WorkingSet._build_master()
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 449, in _build_master
        ws.require(__requires__)
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 742, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 639, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: logilab-common>=0.60.0
    (venv)root@precise64:/vagrant# pip install logilab-common
    Downloading/unpacking logilab-common
      Downloading logilab-common-0.63.2.tar.gz (196kB): 196kB downloaded
      Running setup.py (path:/var/lib/wflow/venv/build/logilab-common/setup.py) egg_info for package logilab-
    common
        /usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'test_require'
          warnings.warn(msg)

        package init file './test/__init__.py' not found (or not a regular file)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /var/lib/wflow/venv/lib/python3.2
    /site-packages (from logilab-common)
    Installing collected packages: logilab-common
      Running setup.py install for logilab-common
        /usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'test_require'
          warnings.warn(msg)
        package init file './test/__init__.py' not found (or not a regular file)
        package init file './test/__init__.py' not found (or not a regular file)
        changing mode of build/scripts-3.2/pytest from 644 to 755
          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/textutils.py", line 59
            u'\xa1': u'!',    # INVERTED EXCLAMATION MARK
                  ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/umessage.py", line 52
            return u' '.join(parts)
                      ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/registry.py", line 1008
            return u'<Predicate %s at %x>' % (self.__class__.__name__, id(self))
                                         ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/ureports/__init__.py", line 45

            return u' '.join([node.data for node in get_nodes(child, Text)])
                      ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/ureports/text_writer.py", line 30
            TITLE_UNDERLINES = [u'', u'=', u'-', u'`', u'.', u'~', u'^']
                                  ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/ureports/html_writer.py", line 37
            attrs = u''
                      ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_xmlutils.py", line 29
            pi_data = u" \t \n "
                               ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_umessage.py", line 46
            self.assertEqual(subj, u'À LA MER')
                                              ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_testlib.py", line 176
            self.assertRaises(AssertionError, self.tc.assertMultiLineEqual, 3.12, u"toto")
                                                                                        ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_decorators.py", line 116
            @cached(cacheattr=u'_foo')
                                    ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_date.py", line 134
            self.assertEqual(ustrftime(date, '%Y-%m-%d %H:%M:%S'), u'1328-03-12 06:30:00')
                                                                                        ^
        SyntaxError: invalid syntax

          File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/test/unittest_textutils.py", line 238
            data = [(u'\u0153nologie', u'oenologie'),
                                    ^
        SyntaxError: invalid syntax

        package init file './test/__init__.py' not found (or not a regular file)
        Installing /var/lib/wflow/venv/lib/python3.2/site-packages/logilab_common-0.63.2-py3.2-nspkg.pth
        changing mode of /var/lib/wflow/venv/bin/pytest to 755
        package init file './test/__init__.py' not found (or not a regular file)
    Successfully installed logilab-common
    Cleaning up...
    (venv)root@precise64:/vagrant# prospector
    Traceback (most recent call last):
      File "/var/lib/wflow/venv/bin/prospector", line 9, in <module>
        load_entry_point('prospector==0.9.9', 'console_scripts', 'prospector')()
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 356, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 2431, in load_entry_point
        return ep.load()
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pkg_resources.py", line 2147, in load
        ['__name__'])
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/prospector/run.py", line 7, in <module>
        from prospector import tools, blender, postfilter
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/prospector/tools/__init__.py", line 6, in <module>
        from prospector.tools.pylint import PylintTool
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/prospector/tools/pylint/__init__.py", line 6, in <module>
        from pylint.utils import UnknownMessage
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/pylint/utils.py", line 33, in <module>
        from logilab.common.textutils import normalize_text
      File "/var/lib/wflow/venv/lib/python3.2/site-packages/logilab/common/textutils.py", line 59
        u'\xa1': u'!',    # INVERTED EXCLAMATION MARK
              ^
    SyntaxError: invalid syntax

**Comment by carlio** [comment]
Prospector supports Python 3.3+ but not below - this is true of most of the underlying tools as well so it is not possible to support 3.2.
