### ISSUE TITLE
pkg_resources.DistributionNotFound: pep8-naming>=0.2.2

### ISSUE THREAD

**Issue by weldpua2008** [landscapeio/prospector#110]
Hello,
I try to build prospector on Ubuntu 12.04 but I got an runtime error
    # pip install prospector==0.9.9
```

Collecting prospector==0.9.9
  Using cached prospector-0.9.9.tar.gz
Collecting pylint>=1.4 (from prospector==0.9.9)
  Using cached pylint-1.4.3-py2.py3-none-any.whl
Collecting pylint-celery>=0.3 (from prospector==0.9.9)
  Using cached pylint-celery-0.3.tar.gz
Collecting pylint-django>=0.6 (from prospector==0.9.9)
  Using cached pylint-django-0.6.tar.gz
Collecting pylint-plugin-utils>=0.2.3 (from prospector==0.9.9)
  Using cached pylint-plugin-utils-0.2.3.tar.gz
Collecting pylint-common>=0.2.1 (from prospector==0.9.9)
  Using cached pylint-common-0.2.1.tar.gz
Collecting requirements-detector>=0.3 (from prospector==0.9.9)
  Using cached requirements-detector-0.3.tar.gz
Collecting setoptconf>=0.2.0 (from prospector==0.9.9)
  Using cached setoptconf-0.2.0.tar.gz
Collecting dodgy>=0.1.6 (from prospector==0.9.9)
  Using cached dodgy-0.1.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/dist-packages (from prospector==0.9.9)
Collecting mccabe>=0.2.1 (from prospector==0.9.9)
  Using cached mccabe-0.3-py2.py3-none-any.whl
Collecting pyflakes>=0.8.1 (from prospector==0.9.9)
  Using cached pyflakes-0.8.1-py2.py3-none-any.whl
Collecting pep8>=1.6.0 (from prospector==0.9.9)
  Using cached pep8-1.6.2-py2.py3-none-any.whl
Collecting pep8-naming>=0.2.2 (from prospector==0.9.9)
  Using cached pep8_naming-0.2.2-py2.py3-none-any.whl
Collecting pep257>=0.3.2 (from prospector==0.9.9)
  Using cached pep257-0.5.0.tar.gz
Collecting logilab-common>=0.53.0 (from pylint>=1.4->prospector==0.9.9)
  Using cached logilab-common-0.63.2.tar.gz
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_require'
      warnings.warn(msg)
    package init file './test/__init__.py' not found (or not a regular file)
Collecting six (from pylint>=1.4->prospector==0.9.9)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting astroid>=1.3.6 (from pylint>=1.4->prospector==0.9.9)
  Using cached astroid-1.3.6-py2.py3-none-any.whl
Collecting argparse (from dodgy>=0.1.6->prospector==0.9.9)
  Using cached argparse-1.3.0-py2.py3-none-any.whl
Installing collected packages: argparse, astroid, six, logilab-common, pep257, pep8-naming, pep8, pyflakes, mccabe, dodgy, setoptconf, requirements-detector, pylint-common, pylint-plugin-utils, pylint-django, pylint-celery, pylint, prospector

  Compiling /tmp/pip-build-KR4bMY/astroid/astroid/tests/testdata/python3/data/module.py ...


  Compiling /tmp/pip-build-KR4bMY/astroid/astroid/tests/testdata/python3/data/module2.py ...




  Running setup.py install for logilab-common
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_require'
      warnings.warn(msg)
    package init file './test/__init__.py' not found (or not a regular file)
    package init file './test/__init__.py' not found (or not a regular file)
    changing mode of build/scripts-2.7/pytest from 644 to 755
    package init file './test/__init__.py' not found (or not a regular file)
    Installing /usr/local/lib/python2.7/dist-packages/logilab_common-0.63.2-nspkg.pth
    changing mode of /usr/local/bin/pytest to 755
    package init file './test/__init__.py' not found (or not a regular file)
  Running setup.py install for pep257
    changing mode of build/scripts-2.7/pep257 from 644 to 755
    changing mode of /usr/local/bin/pep257 to 755




  Running setup.py install for dodgy
    changing mode of build/scripts-2.7/dodgy from 644 to 755
    changing mode of /usr/local/bin/dodgy to 755
  Running setup.py install for setoptconf
  Running setup.py install for requirements-detector
    changing mode of build/scripts-2.7/detect-requirements from 644 to 755
    changing mode of /usr/local/bin/detect-requirements to 755
  Running setup.py install for pylint-common
  Running setup.py install for pylint-plugin-utils
  Running setup.py install for pylint-django
  Running setup.py install for pylint-celery
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2), "no error"
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:5: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2) #this should generate a warning
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:7: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, ), "no error"
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:8: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, )
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:9: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2, 3 == 5), "no error"
/tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_assert_2uple.py:11: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (True, 'error msg') #this should generate a warning
  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/abstract_abc_methods.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/abstract_class_instantiated_py2.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/abstract_class_instantiated_py3.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/abstract_method_py2.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/abstract_method_py3.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/class_members_py27.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/class_members_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/no_name_in_module.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/old_style_class_py27.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/raising_non_exception_py3.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/unbalanced_tuple_unpacking_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/undefined_variable_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/functional/yield_outside_func.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_bad_exception_context_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_continue_not_in_loop.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_e0108.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_exec_used_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_keyword_repeat.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_kwoa_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_noerror_mcs_attr_access.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_noerror_unused_variable_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_return_outside_func.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_return_yield_mix_py_33.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_syntax_error.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_undefined_metaclass_var_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_unused_import_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_used_before_assignment_py30.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/func_w0705.py ...


  Compiling /tmp/pip-build-KR4bMY/pylint/pylint/test/input/syntax_error.py ...
  Sorry: IndentationError: ('expected an indented block', ('/tmp/pip-build-KR4bMY/pylint/pylint/test/input/syntax_error.py', 2, 5, "print('hop')\n"))

  Running setup.py install for prospector
    Installing prospector script to /usr/local/bin
Successfully installed argparse-1.3.0 astroid-1.3.6 dodgy-0.1.6 logilab-common-0.63.2 mccabe-0.3 pep257-0.5.0 pep8-1.6.2 pep8-naming-0.2.2 prospector-0.9.9 pyflakes-0.8.1 pylint-1.4.3 pylint-celery-0.3 pylint-common-0.2.1 pylint-django-0.6 pylint-plugin-utils-0.2.3 requirements-detector-0.3 setoptconf-0.2.0 six-1.9.0
```

root@RDE-1.3:~# prospector
```

Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8-naming>=0.2.2
```

**Comment by carlio** [comment]
This may be fixed as part of #115 (and is similar to #113). I don't really know why it happens yet - please try the new release (0.10.1) in case it helps?

**Comment by weldpua2008** [comment]
Hi,
Thank you. Now I don't see this problem.

**Comment by carlio** [comment]
Excellent!

**Comment by nalourie** [comment]
Hi, 
I'm actually getting this issue as well. I'm running it on Windows, python 2.7.7, and I tried both prospector 0.10 and 0.10.1.
