### ISSUE TITLE
prospector fails to start  after pip2.7 install --upgrade 'prospector>=0.10' 

### ISSUE THREAD

**Issue by weldpua2008** [landscapeio/prospector#136]
Hi,
I use prospector in CI to test code and form the pylint-compitable report.
It Always worked until it was installed logilab-common-1.0.2:
lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

I run /usr/local/bin/pip2.7 install --upgrade 'prospector>=0.10'
```
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/var/lib/jenkins/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: prospector>=0.10 in /usr/local/lib/python2.7/dist-packages/prospector-0.10.2-py2.7.egg
Requirement already up-to-date: pylint>=1.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-celery>=0.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-django>=0.6 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-plugin-utils>=0.2.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-common>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: requirements-detector>=0.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: setoptconf>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: dodgy>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: mccabe>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyflakes>=0.8.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8>=1.6.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8-naming>=0.2.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep257>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: logilab-common>=0.53.0 in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Collecting astroid>=1.3.6 (from pylint>=1.4->prospector>=0.10)
  Downloading astroid-1.3.7-py2.py3-none-any.whl (183kB)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from logilab-common>=0.53.0->pylint>=1.4->prospector>=0.10)
Installing collected packages: astroid
  Found existing installation: astroid 1.3.6
    Uninstalling astroid-1.3.6:
      Successfully uninstalled astroid-1.3.6
Successfully installed astroid-1.3.7
```

So now I have same prospector:
```
root@ubuntu-rde-test:~# pip list|grep prosp
prospector (0.10.2)
```
but it fails
# prospector /opt/pymanager/main.py
```
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (logilab-common 1.0.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('logilab-common<=0.63.0'), set(['astroid']))
```
All this because was installed logilab-common-1.0.2, but:

root@ubuntu-rde-test:~# pip2.7 install --upgrade 'prospector>=0.10'
```
Requirement already up-to-date: prospector>=0.10 in /usr/local/lib/python2.7/dist-packages/prospector-0.10.2-py2.7.egg
Requirement already up-to-date: pylint>=1.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-celery>=0.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-django>=0.6 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-plugin-utils>=0.2.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-common>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: requirements-detector>=0.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: setoptconf>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: dodgy>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: mccabe>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyflakes>=0.8.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8>=1.6.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8-naming>=0.2.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep257>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Collecting logilab-common>=0.53.0 (from pylint>=1.4->prospector>=0.10)
  Using cached logilab-common-1.0.2.tar.gz
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Requirement already up-to-date: astroid>=1.3.6 in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from logilab-common>=0.53.0->pylint>=1.4->prospector>=0.10)
Installing collected packages: logilab-common
  Found existing installation: logilab-common 0.63.0
    Uninstalling logilab-common-0.63.0:
      Successfully uninstalled logilab-common-0.63.0
  Running setup.py install for logilab-common
Successfully installed logilab-common-1.0.2
```

root@ubuntu-rde-test:~# pip install astroid==1.3.7
```
Requirement already satisfied (use --upgrade to upgrade): astroid==1.3.7 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from astroid==1.3.7)
Collecting logilab-common<=0.63.0 (from astroid==1.3.7)
  Using cached logilab-common-0.63.0.tar.gz
Installing collected packages: logilab-common
  Found existing installation: logilab-common 1.0.2
    Uninstalling logilab-common-1.0.2:
      Successfully uninstalled logilab-common-1.0.2
  Running setup.py install for logilab-common
Successfully installed logilab-common-0.63.0
```
root@ubuntu-rde-test:~# pip2.7 install --upgrade 'prospector>=0.10'
```
/usr/local/lib/python2.7/dist-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: prospector>=0.10 in /usr/local/lib/python2.7/dist-packages/prospector-0.10.2-py2.7.egg
Requirement already up-to-date: pylint>=1.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-celery>=0.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-django>=0.6 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-plugin-utils>=0.2.3 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pylint-common>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: requirements-detector>=0.4 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: setoptconf>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: dodgy>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: mccabe>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pyflakes>=0.8.1 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8>=1.6.0 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep8-naming>=0.2.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Requirement already up-to-date: pep257>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from prospector>=0.10)
Collecting logilab-common>=0.53.0 (from pylint>=1.4->prospector>=0.10)
  Using cached logilab-common-1.0.2.tar.gz
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Requirement already up-to-date: astroid>=1.3.6 in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector>=0.10)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from logilab-common>=0.53.0->pylint>=1.4->prospector>=0.10)
Installing collected packages: logilab-common
  Found existing installation: logilab-common 0.63.0
    Uninstalling logilab-common-0.63.0:
      Successfully uninstalled logilab-common-0.63.0
  Running setup.py install for logilab-common
Successfully installed logilab-common-1.0.2
```
root@ubuntu-rde-test:~# pip install logilab-common==0.63.0
```
Collecting logilab-common==0.63.0
  Using cached logilab-common-0.63.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from logilab-common==0.63.0)
Installing collected packages: logilab-common
  Found existing installation: logilab-common 1.0.2
    Uninstalling logilab-common-1.0.2:
      Successfully uninstalled logilab-common-1.0.2
  Running setup.py install for logilab-common
Successfully installed logilab-common-0.63.0
```

**Comment by xrmx** [comment]
@weldpua2008 upgrading astroid to 1.3.8 fixed the issue for me and let me use latest logilab-common.

**Comment by carlio** [comment]
@weldpua2008 can you try again with prospector 0.11 and pylint 1.5? that should fix things (as logilab-common is no longer a dependency)
