### ISSUE TITLE
Fails to run with pylint 1.5

### ISSUE THREAD

**Issue by Boxfire** [landscapeio/prospector#146]
Traceback is below. Commenting out the options reset in linter.py leads to many further problems, so there is certainly more work than fixing the initialization.

```
Traceback (most recent call last):
  File "/home/boxfire/.local/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.10.2', 'console_scripts', 'prospector')()
  File "/home/boxfire/.local/lib/python2.7/site-packages/prospector/run.py", line 143, in main
    prospector.execute()
  File "/home/boxfire/.local/lib/python2.7/site-packages/prospector/run.py", line 50, in execute
    for tool in self.config.get_tools(found_files):
  File "/home/boxfire/.local/lib/python2.7/site-packages/prospector/config/__init__.py", line 43, in get_tools
    self.configured_by[tool_name] = tool.configure(self, found_files)
  File "/home/boxfire/.local/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 189, in configure
    linter.reset_options()
  File "/home/boxfire/.local/lib/python2.7/site-packages/prospector/tools/pylint/linter.py", line 19, in reset_options
    OptionsManagerMixIn.__init__(self, usage=PyLinter.__doc__, quiet=True)
TypeError: unbound method __init__() must be called with OptionsManagerMixIn instance as first argument (got ProspectorLinter instance instead)
```

**Comment by carlio** [comment]
Fixed with release `0.11` which is on pypi now :)
