### ISSUE TITLE
AttributeError: 'ProspectorLinter' object has no attribute 'load_file_configuration'

### ISSUE THREAD

**Issue by syabro** [landscapeio/prospector#147]
After installing prospector today I got
```
Traceback (most recent call last):
  File "/Users/syabro/.virtualenvs/homeowners/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/Users/syabro/.virtualenvs/homeowners/lib/python2.7/site-packages/prospector/run.py", line 143, in main
    prospector.execute()
  File "/Users/syabro/.virtualenvs/homeowners/lib/python2.7/site-packages/prospector/run.py", line 50, in execute
    for tool in self.config.get_tools(found_files):
  File "/Users/syabro/.virtualenvs/homeowners/lib/python2.7/site-packages/prospector/config/__init__.py", line 43, in get_tools
    self.configured_by[tool_name] = tool.configure(self, found_files)
  File "/Users/syabro/.virtualenvs/homeowners/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 190, in configure
    self._pylintrc_configure(pylintrc, linter)
  File "/Users/syabro/.virtualenvs/homeowners/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 124, in _pylintrc_configure
    linter.load_file_configuration(pylintrc)
AttributeError: 'ProspectorLinter' object has no attribute 'load_file_configuration'
```

**Comment by syabro** [comment]
Looks like in pylint 1.5 they switched `logilab.common.configuration.OptionsManagerMixIn` to `pylint.config.OptionsManagerMixIn` which doesn't have this method.

**Comment by carlio** [comment]
Ah, thanks for this report - I was just debugging that myself!
