### ISSUE TITLE
Failure message for pyflakes==1.2.0

### ISSUE THREAD

**Issue by EvgeneOskin** [landscapeio/prospector#165]
Hi,

thank you for the great tool!

I've noticed issue when using prospector with `pyflakes==1.2.0`

I got output bellow
```
Messages
========

.
  Line: None
    pyflakes: failure / Tool pyflakes failed to run (exception was raised)



Check Information
=================
         Started: 2016-05-04 14:37:13.511409
        Finished: 2016-05-04 14:37:47.479206
      Time Taken: 33.97 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_veryhigh, full_pep8, doc_warnings, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: celery, django
       Tools Run: dodgy, mccabe, pep257, pep8, profile-validator, pyflakes, pylint
  Messages Found: 1
```

There are not issues when I use `pyflakes==1.1.0`.

**Comment by carlio** [comment]
Hi @EvgeneOskin , can you run again with the `--die-on-tool-error` flag? That will give a full stack trace to see why it failed, thanks :)

**Comment by EvgeneOskin** [comment]
@carlio Sure, here is stacktrace.
```
$ prospector --die-on-tool-error 
Traceback (most recent call last):
  File "/Users/eoskin/.virtualenvs/lookapp/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/prospector/run.py", line 159, in main
    prospector.execute()
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/prospector/run.py", line 65, in execute
    messages += tool.run(found_files)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/prospector/tools/pyflakes/__init__.py", line 131, in run
    checkPath(filepath, reporter)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/api.py", line 108, in checkPath
    return check(codestr, filename, reporter)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/api.py", line 69, in check
    w = checker.Checker(tree, filename)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/checker.py", line 402, in __init__
    self.handleChildren(tree)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/checker.py", line 724, in handleChildren
    self.handleNode(node, tree)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/checker.py", line 771, in handleNode
    handler(node)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/checker.py", line 1150, in IMPORTFROM
    node.module, alias.name)
  File "/Users/eoskin/.virtualenvs/lookapp/lib/python2.7/site-packages/pyflakes/checker.py", line 198, in __init__
    full_name = module + '.' + self.real_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by carlio** [comment]
@EvgeneOskin hmm that looks like a bug in pyflakes from the top of me head - what repo are you trying it on? then I can reproduce at least. Or try running with pyflakes directly instead of prospector? Sorry to be vague!

**Comment by EvgeneOskin** [comment]
@carlio I agree with you on that looks like a bug in pyflakes. 

I run Pyflakes directly and it fails.

I can not give you the repo link, because I run it on private project.

Thank you for support.
