### ISSUE TITLE
[BUG] prospector2 won't install on Windows apparently since using forward slash instead of os.path.join

### ISSUE THREAD

**Issue by Poikilos** [landscapeio/prospector#623]
The prospector2 package doesn't install on Windows (Python 2.7).
- Additionally, where is prospector2? The pypi page links to here. I can't tell if this is a fork of anything because it doesn't say so in the GitHub interface, but the pypi page says prospector2 is a Python 2 fork of prospector.

**To Reproduce** Steps to reproduce the behavior:

1. Open a Windows Command Prompt
2. `py -2 -m pip install prospector2`
3. See error

**Expected behavior**
- Should install prospector2
- Should use os.path.join

**Screenshots**
```
>py -2 -m pip install prospector2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting prospector2
  Downloading prospector2-0.1.tar.gz (50 kB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 50 kB 1.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\owner\\appdata\\local\\temp\\pip-install-ffhpl_\\prospector2\\setup.py'"'"'; __file__='"'"'c:\\users\\owner\\appdata\\local\\temp\\pip-install-ffhpl_\\prospector2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\owner\appdata\local\temp\pip-pip-egg-info-w5z0au'
         cwd: c:\users\owner\appdata\local\temp\pip-install-ffhpl_\prospector2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\owner\appdata\local\temp\pip-install-ffhpl_\prospector2\setup.py", line 37, in <module>
        _PACKAGE_DATA['prospector2'] += [profile for profile in os.listdir(profiledir)]
    WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\owner\\appdata\\local\\temp\\pip-install-ffhpl_\\prospector2\\prospector2/profiles/profiles\\*.*'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Environment (please complete the following information):**

- OS: Windows 10
- Tool: pip
- Prospector version prospector2-0.1
- Python version 2.7

**Comment by Poikilos** [comment]
Ok, I found the fork and moved the issue to here: https://github.com/landscapeio/prospector2/issues/2
