### ISSUE TITLE
UnicodeDecodeError:'utf-8' codec can't decode byte 0x89

### ISSUE THREAD

**Issue by simminni** [landscapeio/prospector#65]
Prospector is throwing exception for python package "django-http-proxy". Version of package is 0.3.2.

Below is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.6.4', 'console_scripts', 'prospector')()
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/run.py", line 190, in main
    prospector = Prospector(config, paths[0])
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/run.py", line 34, in __init__
    self._determine_adapters()
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/run.py", line 46, in _determine_adapters
    for name, adaptor in autodetect_libraries(self.path):
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/autodetect.py", line 69, in autodetect_libraries
    adaptor_names = find_from_path(path)
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/autodetect.py", line 35, in find_from_path
    names |= find_from_path(item_path)
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/autodetect.py", line 35, in find_from_path
    names |= find_from_path(item_path)
  File "/usr/local/lib/python3.4/dist-packages/prospector-0.6.4-py3.4.egg/prospector/autodetect.py", line 38, in find_from_path
    names |= find_from_imports(fip.read())
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 37: invalid start byte
```

Please let me know if you need any further details to look into this issue..

Could you please look into this ?

**Comment by jquast** [comment]
This issue may be closed.
