### ISSUE TITLE
pylint 1.3.1 (and astroid) fails:  AttributeError: 'Class' object has no attribute '_is_subtype_of'

### ISSUE THREAD

**Issue by jquast** [landscapeio/prospector#75]
I'd like to help remove the bounded constraint of excluding pylint 1.4.

Is there anything we do?

Do we need to make pylint compatible with python2.6 upstream to resolve it?

I have a bug that is resolved in pylint 1.4, but I am unable to pin the requirements without raising a VersionConflict due to the ``_INSTALL_REQUIRES`` in setup.py by @carlio 78369b0c64ffcdea71b36770eacebdd67b6053c5

Bug is simple to reproduce, given a file containing
```python
import json

class JSONCustomEncoder(json.JSONEncoder):
    def default(self, obj):
            super(JSONCustomEncoder, self).default(obj)
```

and using prospector's argument ``--die-on-tool-error``:
```
Traceback (most recent call last):
  File "/Users/jquast/.virtualenvs/prospector/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.7.4', 'console_scripts', 'prospector')()
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/prospector/run.py", line 320, in main
    prospector.execute()
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/prospector/run.py", line 227, in execute
    messages += tool.run()
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 182, in run
    self._linter.check(self._args)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/lint.py", line 585, in check
    self.check_astroid_module(astroid, walker, rawcheckers, tokencheckers)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/lint.py", line 662, in check_astroid_module
    walker.walk(astroid)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/utils.py", line 804, in walk
    self.walk(child)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/utils.py", line 804, in walk
    self.walk(child)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/utils.py", line 801, in walk
    cb(astroid)
  File "/Users/jquast/.virtualenvs/prospector/lib/python2.7/site-packages/pylint/checkers/classes.py", line 351, in visit_function
    and klass._is_subtype_of(overridden_frame.qname())):
AttributeError: 'Class' object has no attribute '_is_subtype_of'
```

This was resolved in Nov. 23rd release, https://bitbucket.org/logilab/pylint/commits/6ef255203c84ed2210bf81be4c64cd1f566f953f

**Comment by jquast** [comment]
reference: #73, #76, #79

**Comment by carlio** [comment]
The 0.8 release which just appeared will fix this, see https://github.com/landscapeio/prospector/issues/73#issuecomment-68531424

**Comment by carlio** [comment]
0.8 is now on pypi! Sorry for the delay, Christmas and all that you know, :cake: and :beers:
