### ISSUE TITLE
`pylint` fails with astroid 1.3.2, common 0.63.2

### ISSUE THREAD

**Issue by laserson** [landscapeio/prospector#76]
```
$ prospector --tool pylint -X
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.7.4', 'console_scripts', 'prospector')()
  File "/usr/local/lib/python2.7/site-packages/prospector/run.py", line 320, in main
    prospector.execute()
  File "/usr/local/lib/python2.7/site-packages/prospector/run.py", line 227, in execute
    messages += tool.run()
  File "/usr/local/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 182, in run
    self._linter.check(self._args)
  File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 585, in check
    self.check_astroid_module(astroid, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 662, in check_astroid_module
    walker.walk(astroid)
  File "/usr/local/lib/python2.7/site-packages/pylint/utils.py", line 804, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/site-packages/pylint/utils.py", line 804, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/site-packages/pylint/utils.py", line 801, in walk
    cb(astroid)
  File "/usr/local/lib/python2.7/site-packages/pylint/checkers/classes.py", line 351, in visit_function
    and klass._is_subtype_of(overridden_frame.qname())):
AttributeError: 'Class' object has no attribute '_is_subtype_of'
```

Seems this problem was fixed with Pylint 1.4:
https://bitbucket.org/logilab/pylint/issue/384

However, `prospector` requires `pylint<1.4`.

**Comment by jquast** [comment]
I went ahead and re-opened #75, a duplicate.  I closed it at the time, it sounded like it was already being addressed but it is still an issue, hopefully it will help others find existing issues next time.

**Comment by jquast** [comment]
You can find a workaround in #73 -- basically, forcefully upgrading pylint to 1.4, clobber pylint's hard-requirement on <1.4 in its requires.txt in the installed egg.

**Comment by carlio** [comment]
The 0.8 release which just appeared will fix this, see https://github.com/landscapeio/prospector/issues/73#issuecomment-68531424
